% return PX and INFO structs and P-Cells for parallel MCMC runs
function [PX,INFO,PV,PP,PR] = get_PxInfoStruct(...
    NC, NL, NB, NT, NPAR, FREE, FIX, X0, lb, ub, Par_names, Par_labels, ...
    ML, NSTAGES, NBs, NB0, In0, In1, In2, sf, fh)
% 2016-03-26 tsonne: needed in SBMRVTMCMCv7 and above,
%   initialize structs used for MCMC runs.
%   ML is maxlag.
% 2016-07-01 TSONNE: NOW SAVES FUNCTION STRINGS AND HANDLES (STRUCTS)
if nargin<14
    NSTAGES = 1;
    NBs     = NB;
    NB0     = 0;
    In0 = []; In1=[];In2=[];
end
if nargin < 19
    sf = [];
    fh = [];
end
INFO = struct('NC',NC,'NL',NL,'NB',NB,'NT',NT,'NPAR',NPAR,'FREE',...
    FREE,'FIX',FIX,'X0',X0,'lb',lb,'ub',ub,'Par_names',{Par_names},...
    'Par_labels',{Par_labels},'NSTAGES',NSTAGES,'NBs',NBs,'NB0',NB0,...
    'In0',In0,'In1',In1,'In2',In2,'sf',sf,'fh',fh);
PX = struct('rnd',nan(NT,NC),...
        'mean',nan(1,NC),...
        'std',nan(1,NC),...
        'perc',nan(5,NC),...
        'mode',nan(1,NC),...
        'ln_mean',nan(1,NC),...
        'ln_std',nan(1,NC),...
        'ln_perc',nan(5,NC),...
        'Tmean',nan,...
        'Tstd',nan,...
        'Tperc',nan(5,1),...
        'Tmode',nan,...
        'Tln_mean',nan,...
        'Tln_std',nan,...
        'Tln_perc',nan(5,NC),...
        'R',nan,...
        'neff',nan,...
        'lag1_corr',nan,...
        'acr',nan,...
        'autocorr',zeros(ML+1,1)); % struct for one parameter
PX = repmat(PX,1,NPAR); % NPAR parameters
PX(1).pdf = nan(NT,NC); % add space for probabilities (only in first 
%                         parameter, as same values for all par.)
%
PV   = cell(NC,1); % model parameter value cell
PP   = cell(NC,1); % log-likelihood value cell
PV(:)= {nan(NT,NPAR)};
PP(:)= {nan(NT,1)};
if nargout>4
    PR   = cell(NC,1); % random number cell
    for a = 1:NC
        PR(a) = {randn(NT,NPAR)};
    end
end
end